[package]
name = "krakend"
description = "Dynamic daemon for the leviathan NZXT Kraken drivers."
version = "0.1.0"

[dependencies]
clap = "2.32.0"
jsonrpc-core = "9.0.0"
libc = "0.2.42"
serde = "1.0"
serde_json = "1.0"
xdg = "2.1.0"
